import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NFTIcons } from "@/src/assets/icon/NFTICons";
import { DefaultLayout } from "@/src/layout/DefaultLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DefaultLayout children={children} />
    </html>
  );
}
